Repository InformedSolutions/JAQU-CAZ-Tariff-Service, pull requests merged in 2021-02, with the labels that each got.

#200 [CAZB-4063] Upgrade Terraform version in pipeline
  .drone.yml
  .drone2.yml
Labels: bug

#201 Promote Tariffs v1.6.1 to Pre-Prod
  .drone.yml
  .drone2.yml
Labels: release

#202 Promote Tariffs v1.6.1 to Production
  .drone.yml
  .drone2.yml
Labels: Tariffs v1.6.1, release

#203 Promote Tariffs v1.7.0 to Pre-Prod
  .drone2.yml
  .github/dependabot.yml
  README.md
  pom.xml
  src/it/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTestIT.java
  src/it/resources/data/json/clean-air-zones.json
  src/it/resources/data/json/sample-clean-air-zones.json
  src/it/resources/data/json/sample-tariff.json
  src/it/resources/data/sql/sample-data.sql
  src/main/java/uk/gov/caz/tariff/amazonaws/StreamLambdaHandler.java
  src/main/resources/application.yml
  src/main/resources/db/changelog/changes/0024.1.0-birmingham-update-boundary-url.yaml
  src/test/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTest.java
  src/test/java/uk/gov/caz/tariff/service/CleanAirZonesRepositoryTest.java
  src/test/java/uk/gov/caz/tariff/service/TariffRepositoryTest.java
Labels: Tariffs v1.7.0, release
