Repository InformedSolutions/JAQU-CAZ-Tariff-Service, pull requests merged in 2021-03, with the labels that each got.

#204 Promote Tariffs v1.7.0 to Production
  .drone2.yml
  .github/dependabot.yml
  README.md
  pom.xml
  src/it/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTestIT.java
  src/it/resources/data/json/clean-air-zones.json
  src/it/resources/data/json/sample-clean-air-zones.json
  src/it/resources/data/json/sample-tariff.json
  src/it/resources/data/sql/sample-data.sql
  src/main/java/uk/gov/caz/tariff/amazonaws/StreamLambdaHandler.java
  src/main/resources/application.yml
  src/main/resources/db/changelog/changes/0024.1.0-birmingham-update-boundary-url.yaml
  src/test/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTest.java
  src/test/java/uk/gov/caz/tariff/service/CleanAirZonesRepositoryTest.java
  src/test/java/uk/gov/caz/tariff/service/TariffRepositoryTest.java
Labels: Tariffs v1.7.0, release

#206 [CAZB-4424] Set PGAudit level to ALL,-READ
  docker/docker-compose.yml
  docker/postgres-with-pgaudit/Dockerfile
  pom.xml
  src/it/resources/docker-compose-it.yml
  src/main/resources/db/changelog/changes/0026.1-0-update-pgaudit-level.yaml
Labels: enhancement

#208 [CAZB-4324] Update `CleanAirZones` and `Tariff` endpoints
  pom.xml
  src/it/java/uk/gov/caz/tariff/CazTestIT.java
  src/it/java/uk/gov/caz/tariff/TariffRepositoryTestIT.java
  src/it/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTestIT.java
  src/it/java/uk/gov/caz/tariff/util/JsonReader.java
  src/it/resources/data/json/birmingham-tariff.json
  src/it/resources/data/json/clean-air-zones.json
  src/it/resources/data/json/sample-clean-air-zones.json
  src/it/resources/data/json/sample-tariff.json
  src/it/resources/data/sql/sample-data.sql
  src/main/java/uk/gov/caz/tariff/dto/InformationUrls.java
  src/main/java/uk/gov/caz/tariff/dto/Tariff.java
  src/main/java/uk/gov/caz/tariff/service/CleanAirZonesRepository.java
  src/main/java/uk/gov/caz/tariff/service/RepositoryUtils.java
  src/main/java/uk/gov/caz/tariff/service/TariffRepository.java
  src/main/resources/application.yml
  src/test/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTest.java
  src/test/java/uk/gov/caz/tariff/service/CleanAirZonesRepositoryTest.java
  src/test/java/uk/gov/caz/tariff/service/TariffRepositoryTest.java
Labels: documentation

#209 [CAZB-4323] Order cazes by `display_order`
  src/main/java/uk/gov/caz/tariff/service/CleanAirZonesRepository.java
  src/test/java/uk/gov/caz/tariff/service/CleanAirZonesRepositoryTest.java
Labels: documentation
